### ISSUE TITLE
Archetype has been crashed using Vaadin 7.5.6 release.

### ISSUE THREAD

**Issue by isccarrasco** [vaadin/archetype-application-example#1]
Hi.

I'm trying to use the archetype with the lastest vaadin version (7.5.6), on my "jetty:run" steep, this crashed after the login page...

I'm thinking that this is for the GWT versión, but i'm not sure...

Can you help me  about where i can change the gwt version to compile and run tests?

Thanks so much...

![captura de pantalla 2015-09-28 a las 0 50 28](https://cloud.githubusercontent.com/assets/5122581/10128689/658f7d0c-657b-11e5-9721-07cee9998a2d.png)

![captura de pantalla 2015-09-28 a las 0 53 38](https://cloud.githubusercontent.com/assets/5122581/10128692/6b544452-657b-11e5-9535-a05f6b5d3b8c.png)

**Comment by Artur-** [comment]
I don't think this project is 100% up to date with the current archetype. You should create a new project using the "vaadin-archetype-application-example" archetype instead - that will work with 7.5.6

**Comment by isccarrasco** [comment]
yes, i did it...
i executed the command.

`mvn archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=vaadin-archetype-application-example -DarchetypeVersion=7.5.6`

then: `mvn install`

next, on the ui module: `mvn jetty:run`

and, then is when i saw the problem that i commented here...

do you have any suggestions or related link to look more information about this case ?

thanks...

**Comment by Artur-** [comment]
Right you are. It seems this was a problem with Vaadin 7.5.6 which has been fixed in 7.5.7. Running the same command with 7.5.7 works properly
